@startuml
hide circle

title Random Event and Victory Points\nJohnathan Flake\nReviewed by: Colin Clifford

class "Random Event" {
	Roll1
	Roll2
	
	GetRoll1()
	GetRoll2()
	EventLookup()
	DisplayResults()
}

class "Player" {
	VictoryPoints
	Faction

	AddVP()
	PickFaction()
	DisplayConditions()
}

Class "Scenario" {
	Scenario
	Players
	Factions

	ListFactions()
	AssignFaction()
	AwardVP()
}


@enduml