@startuml
title Terrain Improvement Classes by John G. and Colin Clifford.
hide circle

interface TerrainImprovementType {
+getMovementCost()
+getCombatEffect()
}

TerrainImprovementType <|-- Blasted
TerrainImprovementType <|-- Bridge
TerrainImprovementType <|-- BridgeGate
TerrainImprovementType <|-- Castle
TerrainImprovementType <|-- City
TerrainImprovementType <|-- DragonTunnel
TerrainImprovementType <|-- Ford
TerrainImprovementType <|-- Portal
TerrainImprovementType <|-- Road
TerrainImprovementType <|-- Town
TerrainImprovementType <|-- Trail
TerrainImprovementType <|-- Vortex

@enduml
