@startuml
title Terrain Classes by John G. and Colin Clifford.
hide circle

interface TerrainType {
+getMovementCost()
+getCombatEffect()
}

TerrainType <|-- Broken
TerrainType <|-- Clear
TerrainType <|-- Cultivated
TerrainType <|-- Forest
TerrainType <|-- Glacier
TerrainType <|-- Karoo
TerrainType <|-- River
TerrainType <|-- Lake
TerrainType <|-- Moat
TerrainType <|-- Mountain
TerrainType <|-- Rough
TerrainType <|-- Swamp
TerrainType <|-- Woods
TerrainType <|-- BottomlessPlungehole
TerrainType <|-- GatewayOfEvil

@enduml
