@startuml
hide circle 

skinparam class {

        ArrowColor Black
        
}


title  <b>Class Over View of Sword & Sorcery</b>\nAuthor: David Klingenberg  



package "Map Related Objects" #DDDDDD {
Hex  -- Vortex : Vortex only spawn in Vortex hexes 
Hex *--  Stack
Province *-- ”<b>1..*</b>”Hex
Board *-- “<b>1..*</b>”Province 
}



package “Unit Related Objects” #ff0000 {
MovableUnit <|- Character
Character *- TalismanOfOrb
MovableUnit <|-- Monster
MovableUnit <|-- ArmyUnit
ArmyUnit <|- FlyingUnit

Stack o-  MovableUnit
}


package “Player Turn Objects” #0000ff{
Player  o-- “<b>6..1</b>” Army 
Dipolomacy -*  Player
Army o-- “<b>*..1</b>” MovableUnit_Charter
Character – Spell : Affects unit(s),\nmovement,\nor hexes
Army o- “<b>*..1</b>”MovableUnit
}

@enduml
