@startuml
hide circle
title <b>Master Class Diagram<b>\nAuthors: Keith Drew, Ian Westrope

Stack -right* Hex

MoveableUnit "0..*" --o Stack

ArmyUnit -up-|> MoveableUnit

UnitHashMap -- MoveableUnit : Tracks MoveableUnits and their previous moves

DiplomacyHex -up-|> Hex
MapHex -up-|> Hex

Monster .up.|> MoveableUnit 

HexMap *-up- Hex 

MainMap -up-|> HexMap

DiplomacyMap -up-|> HexMap
DiplomacyMap -- BuildDiplomacyMapFile : The built file initializes the map (?)

HexPainter -up- Hex : HexPainter paints the hex images

HexEdge -* Hex

EdgeElement "0..6" -up-o HexEdge
HexEdgeType "0..6" -up-o HexEdge

TerrainType -down-* Hex

ImprovedTerrainType "0..*" -down-o Hex

StellarConfiguration -down- SolarDisplay : The display depends on the configuration

SolarDisplay -down- HUD : Hud displays the solar state

HUD -down- MapView : The HUD surrounds the MapView during play

HEExtensions -up-|> EdgeElement
TTExtensions -up-|> TerrainType
ITTExtensions -up-|> ImprovedTerrainType

'package DisjointClasses <<Rect>> {
'class ArmyCombatResultsTable #blue 
'class RandomEventTable #blue
'class ScenarioConfigurationReader #blue 
'class Unit #red
'}

note as N1
Color coded to packages
Red - Located in a <default package>
Blue - Located in sworsorc/client
Green - Located in sworsorc/model
Yellow - Located in sworsorc/utilities
end note

class MoveableUnit #green {
}

class ArmyUnit #green {
}

class Stack #green {
}

class UnitHashMap #green {
}

class Hex #green {
}

class DiplomacyHex #green {
}

class MapHex #green {
}

class HexMap #green {
}

class MainMap #green {
}

class DiplomacyMap #green {
}

class EdgeElement #green {
}

class HexEdgeType #green {
}

class HexEdge #green {
}

class TerrainType #green {
}

class ImprovedTerrainType #green {
}

class HEExtensions #green {
}

class TTExtensions #green {
}

class ITTExtensions #green {
}

class Monster #red {
}

class BuildDiplomacyMapFile #red {
}

class HexPainter #red {
}

class SolarDisplay #blue {
}

class HUD #blue {
}

class StellarConfiguration #blue {
}

class MapView #blue {
}

class HexPainter #blue {
}



@enduml