@startuml
hide circle
title <b>Master Class Diagram<b>\nAuthors: Keith Drew, Ian Westrope

Stack -right* Hex

MoveableUnit "0..*" --o Stack

ArmyUnit -up-|> MoveableUnit

UnitHashMap -- MoveableUnit : Tracks MoveableUnits and their previous moves

DiplomacyHex -up-|> Hex
MapHex -up-|> Hex

Monster .up.|> MoveableUnit 

HexMap *-up- Hex 

MainMap -up-|> HexMap

DiplomacyMap -up-|> HexMap
DiplomacyMap -- BuildDiplomacyMapFile : The built file initializes the map (?)

HexPainter -up- Hex : HexPainter paints the hex images

HexEdge -* Hex

EdgeElement "0..6" -up-o HexEdge
HexEdgeType "0..6" -up-o HexEdge

TerrainType -down-* Hex

ImprovedTerrainType "0..*" -down-o Hex

StellarConfiguration -down- SolarDisplay : The display depends on the configuration

SolarDisplay -down- HUD : Hud displays the solar state

HUD -down-MapView : The HUD surrounds the MapView during play

HEExtensions -up-|> EdgeElement
TTExtensions -up-|> TerrainType
ITTExtensions -up-|> ImprovedTerrainType

'package DisjointClasses <<Rect>> {
'class ArmyCombatResultsTable #FFFF00 
'class RandomEventTable #FFFF00 
'class ScenarioConfigurationReader #FFFF00 
'class Unit #999900 
'}

note as N1
Color coded to packages
Red - Located in a <default package>
Blue - Located in sworsorc/client
Green - Located in sworsorc/model
Yellow - Located in sworsorc/utilities
end note

class MoveableUnit #999900 {
}

class ArmyUnit #999900 {
}

class Stack #999900 {
}

class UnitHashMap #999900 {
}

class Hex #66CC00 {
}

class DiplomacyHex #66CC00 {
}

class MapHex #66CC00 {
}

class HexMap #66CC00 {
}

class MainMap #66CC00 {
}

class DiplomacyMap #66CC00 {
}

class EdgeElement #00CC00 {
}

class HexEdgeType #00CC00 {
}

class HexEdge #00CC00 {
}

class TerrainType #00CC00 {
}

class ImprovedTerrainType #00CC00 {
}

class HEExtensions #00CC00 {
}

class TTExtensions #00CC00 {
}

class ITTExtensions #00CC00 {
}

class Monster #F21818 {
}

class BuildDiplomacyMapFile #F21818 {
}

class HexPainter #F21818 {
}

class SolarDisplay #3333FF {
}

class HUD #3333FF {
}

class StellarConfiguration #3333FF {
}

class MapView #3333FF {
}

class HexPainter #3333FF {
}

@enduml