@startuml
hide circle
title <b>Master Class Diagram<b> Authors: Keith Drew, Ian Westrope

Game *-- MainMap
Game *-- "2..7" Player
Game *-- "0..*" Alliance 
Game - Scenario : Scenario Initiates\nGame
Scenario "14" -* StaticDataStructure
Alliance <|-down- NPCAlliance
Alliance - Player : An alliance links two\nplayers/NPC turns together
Province "25" -down-* MainMap
Hex "0..*" -down-* Province
SpecialHex -up-|> Hex
TeleportHex -up-|> SpecialHex
VortexHex -up-|> SpecialHex
PlungeholeHex -up-|> SpecialHex
Town -up-|> SpecialHex
City -up-|> SpecialHex
Castle -up-|> SpecialHex
Capital -up-|> SpecialHex

Stack -right-* Hex
MoveableUnit "0..*" -down-o Stack

Vortex -up-|> MoveableUnit
Monster -up-|> MoveableUnit
ArmyUnit -up-|> MoveableUnit
FlyingUnit -up-|> MoveableUnit
Character -left-|> Monster
RangedArmyUnit -up-|> ArmyUnit
MeleeArmyUnit -up-|> ArmyUnit
Dragon -up-|> Monster
Demon -up-|> Monster
Troll -up-|> Monster
KillerPenguin -up-|> Monster
TyrannosauriReges -up-|> Monster
Spectre -up-|> Monster
FlyingUnit -- Dragon : Dragons are\nflying monsters
TalismanOfOrb -up-o Character
CasterCharacter -up-|> Character
FighterCharacter -up-|> Character

StaticDataStructure *- "7" GameChart

GameTerrainChart -up-|> GameChart
GameCombatResultsChart -up-|> GameChart
GameRandomEventChart -up-|> GameChart
GameSpellChart --up-|> GameChart
GameKillerPenguinEntryChart --up-|> GameChart
GameEmissaryResultsChart --up-|> GameChart
GameDiplomaticGroupChart --up-|> GameChart

class Game #529292 {
}

class MainMap #529292 {
}

class Player #529292 {
}

class Alliance #529292 {
}

class NPCAlliance #529292 {
}

class Province #529292 {
}

class Hex #529292 {
}

class SpecialHex #529292 {
}

class TeleportHex #529292 {
}

class VortexHex #529292 {
}

class PlungeholeHex #529292 {
}

class Town #529292 {
}

class Castle #529292 {
}

class Capital #529292 {
}

class City #529292 {
}

class Stack #529292 {
}

class MoveableUnit #529292 {
}

class Vortex #529292 {
}

class FlyingUnit #529292 {
}

class ArmyUnit #529292 {
}

class MeleeArmyUnit #529292 {
}

class RangedArmyUnit #529292 {
}

class Monster #529292 {
}

class Dragon #529292 {
}

class Demon #529292 {
}

class Troll #529292 {
}

class TyrannosauriReges #529292 {
}

class Spectre #529292 {
}

class KillerPenguin #529292 {
}

class Character #529292 {
}

class CasterCharacter #529292 {
}

class FighterCharacter #529292 {
}

class TalismanOfOrb #529292 {
}

class Scenario #529292 {
}

class StaticDataStructure #529292 {
}

class GameChart #529292 {
}

class GameTerrainChart #529292 {
}

class GameCombatResultsChart #529292 {
}

class GameRandomEventChart #529292 {
}

class GameSpellChart #529292 {
}

class GameKillerPenguinEntryChart #529292 {
}

class GameEmissaryResultsChart #529292 {
}

class GameDiplomaticGroupChart #529292 {
}



@enduml