@startuml
hide circles
title <b>Hex Class Diagram<b> Author: Ian Westrope, Keith Drew

MainMap *-- "1..*" MapHex
Hex <|-- MapHex
Hex <|-- DiplomacyHex
DiplomacyMap *-- "1..*" DiplomacyHex


class MainMap #529292 {
 -HashMap <String, MapHex> mainMap
 -String hexNumber, northHexNumber, northEastHexNumber, 
            southEastHexNumber, southHexNumber, southWestHexNumber,
            northWestHexNumber, terrainKey, providenceName, hexName;
 -boolean cityHex, vortexHex, castleHex, capitalHex, townHex;
-int portalHex
 -DocumentBuilderFactory factory
 -DocumentBuilder builder
 -Document doc
 -File file = new File("resources/MainMap.xml")
 -HashMap<String, ArrayList<String>> edgeDirectionList
-{static}MainMap INSTANCE
-MainMap()
-BuildmainMap()
-CleanHex()
-GetDoc() :  NodeList
{static} GetMainMap() :  MainMap
}

class Hex #529292 {
-String[] hexagon
-Hex(String ID, String northHexID, String northEastHexID, String southEastHexID, 
          String southHexID, String southWestHexID, String northWestHexID)
+GetID() : String
+GetIDofNorthEastHexagon() : String 
-SetID(String ID)
-SetIDofNorthEastHexagon(String ID)
}

class MapHex #529292 {
-String hexName, terrainKey, providenceName;
-boolean cityHex, vortexHex, castleHex, capitalHex, 
townHex
-int portalHex
-HashMap<String, ArrayList<String>> hexEdgeMap
-ArrayList<String> northList, northWestList, northEastList, 
southList, southEastList, southWestList;
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence,
                  HashMap<String, ArrayList<String>> edgesOfHex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String, ArrayList<String>> edgesOfHex,String nameHex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String, ArrayList<String>> edgesOfHex, boolean hexIsCity, 
                  boolean hexIsCapital, boolean hexIsCastle, boolean hexIsTown, String nameHex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String, ArrayList<String>> edgesOfHex, boolean hexVortex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String,ArrayList<String>> edgesOfHex, int portalNumber)
+IsCapitalHex() : boolean
+IsCastleHex() : boolean
+IsCityHex() : boolean
+IsCityTownCastel() : boolean
+IsPortalHex() : boolean
+IsTownHex() : boolean 
+IsVortexHex() : boolean 
+ModifyTerrainCode(String keyterrain)
+RemoveHexEdgeAdditions(int edgedDirection,String hexEdgeCode)
}

class DiplomacyMap #529292 {
-HashMap <String, DiplomacyHex> DiplomacyMap
-String hexNumber, northHexNumber, northEastHexNumber, 
            southEastHexNumber, southHexNumber, southWestHexNumber,
            northWestHexNumber, specialCode
 -DocumentBuilderFactory factory;
 -DocumentBuilder builder
-Document doc
-File file
{static}DiplomacyMap INSTANCE
-DiplomacyMap()
-BuildDiplomacyMap()
{static}GetDiplomacyMap() : DiplomacyMap
+GetDiplomacyHex(String id) : DiplomacyHex 
}

class DiplomacyHex #529292 {
-boolean playerHex, neturalHex
+public DiplomacyHex(String id, String northHexID, String northEastHexID, 
                            String southEastHexID, String southHexID, String southWestHexID, 
                            String northWestHexID, String specialHexCode)
+DiplomacyHex(String id, String northHexID, String northEastHexID, 
                            String southEastHexID, String southHexID, String southWestHexID, 
                            String northWestHexID, String specialHexCode)
-SetPlayerHex()
-SetNeturalHex()
+GetIsPlayerHex() : boolean 
+GetIsNeturalHex() : boolean 
}

@enduml