@startuml
hide circles
title <b>Data Structures Class Diagram<b> Author: Ian Westrope

class Hex #529292 {
-hexID
+getTerrainDefenseBonus()
}

class VortexHex #529292 {
+spawnVortex()
}

class PlungeholeHex #529292 {
+eatUnits()
}

class Town #529292 {
-defenseRating
}

class City #529292 {
-defenseRating
}

class Castle #529292 {
-defenseRating
}

class Capital #529292 {
-defenseRating
}

class TeleportHex #529292 {
-defenseRating
}

Hex <|-- VortexHex
Hex <|-- PlungeholeHex
Hex <|-- Town
Hex <|-- City
Hex <|-- Castle
Hex <|-- Capital
Hex <|-- TeleportHex


@enduml