@startuml
hide circle
title <b>Overview Class Diagram<b> Author: Keith Drew

Game *- MainMap
Game *- "2..7" Player
Game *- "0..*" Alliance 
Game - Chart : The game finds chart data by\naccessing chart classes.
Alliance - Player : An alliance links two\nplayers/NPC turns together
Hex "0..*" -down-* MainMap
Hex <|-right- MapHex
Stack -left-* MapHex
MoveableUnit "0..*" -left-o Stack

class Game #529292 {
-players[]
-alliances[]
-scenarioNumber
-victoryConditions
-currentGameTurnNumber
-currentPlayerTurnNumber
+Game( Scenario )
}

class MainMap #529292 {
 -HashMap <String, MapHex> mainMap
 -String hexNumber, northHexNumber, northEastHexNumber, 
            southEastHexNumber, southHexNumber, southWestHexNumber,
            northWestHexNumber, terrainKey, providenceName, hexName;
 -boolean cityHex, vortexHex, castleHex, capitalHex, townHex;
-int portalHex
 -DocumentBuilderFactory factory
 -DocumentBuilder builder
 -Document doc
 -File file = new File("resources/MainMap.xml")
 -HashMap<String, ArrayList<String>> edgeDirectionList
-{static}MainMap INSTANCE
-MainMap()
-BuildmainMap()
-CleanHex()
-GetDoc() :  NodeList
{static} GetMainMap() :  MainMap
}

class Player #529292 {
-playerNumber
-playerVictoryPoints
+AddVictoryPoints()
}

class Alliance #529292 {
-alliedPlayers[]
+AlliedTurn()
}

class Hex #529292 {
-String[] hexagon
-Hex(String ID, String northHexID, String northEastHexID, String southEastHexID, 
          String southHexID, String southWestHexID, String northWestHexID)
+GetID() : String
+GetIDofNorthEastHexagon() : String 
-SetID(String ID)
-SetIDofNorthEastHexagon(String ID)
}

class MapHex #529292 {
-String hexName, terrainKey, providenceName;
-boolean cityHex, vortexHex, castleHex, capitalHex, 
townHex
-int portalHex
-HashMap<String, ArrayList<String>> hexEdgeMap
-ArrayList<String> northList, northWestList, northEastList, 
southList, southEastList, southWestList;
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence,
                  HashMap<String, ArrayList<String>> edgesOfHex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String, ArrayList<String>> edgesOfHex,String nameHex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String, ArrayList<String>> edgesOfHex, boolean hexIsCity, 
                  boolean hexIsCapital, boolean hexIsCastle, boolean hexIsTown, String nameHex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String, ArrayList<String>> edgesOfHex, boolean hexVortex)
+MapHex(String id, String northHexID, String northEastHexID, 
                  String southEastHexID, String southHexID, String southWestHexID, 
                  String northWestHexID, String keyTerrain, String nameProvidence, 
                  HashMap<String,ArrayList<String>> edgesOfHex, int portalNumber)
+IsCapitalHex() : boolean
+IsCastleHex() : boolean
+IsCityHex() : boolean
+IsCityTownCastel() : boolean
+IsPortalHex() : boolean
+IsTownHex() : boolean 
+IsVortexHex() : boolean 
+ModifyTerrainCode(String keyterrain)
+RemoveHexEdgeAdditions(int edgedDirection,String hexEdgeCode)
}

class Stack #529292 {
-ArmyUnit[]
-Character[]
-Monster[]
+resolveUnitConflicts()
+selectUnits()
+removeUnits()
+addUnits()
}

class MoveableUnit #529292 {
-movementAllowance
-combatStrength
-flyingUnitFlag
+move()
}


class Chart #529292 {
-terrainChart
-combatChart
-randomChart
-spellChart
-kpChart
-emissaryChart
-diplomacyChart
+getChartResults()
}
@enduml