@startuml
hide circles
title <b>Unit Use Case Diagram<b> Author: Ian Westrope

class MoveableUnit #529292 {
      +Int Movement_Allowance
      +Int Combat_Strength
      +Bool Flying_Unit
}

class Character #529292 {
      +Char Race
      +Int Magic_PL
      +Int Magic_Potential
      +Int Magic_Color
      +Int Home_Hex
      +Int Magic_Profile
      +Int Magic_Resistance
      +Int Leadership
      +Int Diplomatic
      +Int Fighting
      +Int Endurance
}

class ArmyUnit #529292 {
      +Char Unit_Type
      +Char Unit_Race
      +Int Demoralized_Strength
}

class MeeleeArmyUnit #529292 {
      +void Charge()
}

class RangedArmyUnit #529292 {

}


class Monster #529292 {
      +Int Magic_PL
      +Int Magic_Potential
      +Int Magic_Color
      +Int Magic_Resitance
      +Int Fighting
      +Int Endurance
      +Int Combat_Strenght
      +Char Owner
      +void ChangeOwner()
}

class Demon #529292 {
      +Bool Bound
}

class Dragon #529292 {
      +void Breathe_Fire()
}

class Troll #529292 {
      +void Regenerate()
}

class Spectre #529292 

class TyrannosauriRegs #529292 

class TalismanOfOrb #529292 

Class FlyingUnit #529292 

MoveableUnit <|-- Monster
MoveableUnit <|-- FlyingUnit
MoveableUnit <|-- ArmyUnit

Monster <|-- Character
Monster <|-- Demon
Monster <|-- Troll
Monster <|-- TyrannosauriRegs
Monster <|-- Spectre
Monster <|-- Dragon

ArmyUnit <|-- RangedArmyUnit
ArmyUnit <|-- MeeleeArmyUnit

Character o-- TalismanOfOrb

FlyingUnit -- Dragon

@enduml