@startuml
title   Solar Cycle\nAuthor:  David Klingenberg

state “Red Sun\n[A,C, .., K]” as starta{
state “Suns in Balance” as sb1
state “Suns in Balance” as sb2
state “Red Sun Ascendant\n Blue Sun Descendent” as ra
state “Red Sun Descendent\nBlue Sun Ascendant” as rd
note “Depending on start code,\nit is possible to start in\nany state and at any point\nin the count\n[ 1<=c<=5] or [1<=c<=6]. “ as n

ra : Count <= 5
rd : Count <= 5
sb2 : Count <= 6
sb1 : Count <= 6

ra --> sb1 : Count  > 5
sb1  --> rd : Count > 6 
rd --> sb2 : Count  > 5
sb2 --> ra : Count > 6
}

state “Red Sun\n[B,D, .., L]” as startb{
state “Suns in Balance” as sb3
state “Suns in Balance” as sb4
state “Red Sun Ascendant\n Blue Sun Descendent” as ra1
state “Red Sun Descendent\nBlue Sun Ascendant” as rd1
note “Depending on start code,\nit is possible to start in\nany state and at any point\nin the count\n[ 1<=c<=5] or [1<=c<=6]. “ as n1

ra1 : Count <= 6
rd1 : Count <= 6
sb3 : Count <= 5
sb4 : Count <= 5

ra1 --> sb3 : Count  > 6
sb3  --> rd1 : Count > 5 
rd1 --> sb4 : Count  > 6
sb4 --> ra1 : Count > 5
}

[*] --> starta : Start Red\nSun at\n[A,C, .., K]
[*] --> startb : Start Red\nSun at\n[B,D, .., L]
starta --> [*] : Scenario\nEnds
startb --> [*] : Scenario\nEnds

@enduml
