/*
 * MenuUI.java
 * Keith Drew
 * Created on Feb 17, 2014, 9:09:11 AM
 */
package Menu;

public class MenuUI extends javax.swing.JFrame {

    /** Creates new form MenuUI */
    public MenuUI() {
        initComponents();
        this.setSize(420,440); // Setting window size, default is too small. 
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("New Game");
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 210, 110, 30);

        jButton2.setText("Resume Game");
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 240, 110, 30);

        jButton3.setText("Save Game");
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 270, 110, 30);

        jButton4.setText("Options");
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 300, 110, 30);

        jButton5.setText("About");
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 330, 110, 30);

        jButton6.setText("Exit");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 360, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Menu.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
System.exit(0);
}//GEN-LAST:event_jButton6MouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
