package MainSwordSorcery;


import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class SwordSorceryGUI extends javax.swing.JFrame {
    private Component frame;

    /**
     * Creates new form CelsiusConverterGUI
     */

    
    public SwordSorceryGUI() {
        setLayout(new BorderLayout());
	setContentPane(new JLabel(new ImageIcon("images/Swords-Sorcery-Counters-A.jpg")));
        setLayout(new FlowLayout());
        
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newGameFileMenuItem = new javax.swing.JMenuItem();
        loadGameFileMenuItem = new javax.swing.JMenuItem();
        saveGameFileMenuItem = new javax.swing.JMenuItem();
        optionsFileMenuItem = new javax.swing.JMenuItem();
        exitFileMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutHelpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sword and Sorcery!");
        setBackground(new java.awt.Color(204, 0, 51));
        setForeground(java.awt.Color.white);

        jButton1.setText("jButton1");

        mainMenu.setBackground(new java.awt.Color(255, 255, 51));
        mainMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        fileMenu.setText("File");

        newGameFileMenuItem.setText("New Game");
        newGameFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newGameFileMenuItem);

        loadGameFileMenuItem.setText("Load Game");
        loadGameFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadGameFileMenuItem);

        saveGameFileMenuItem.setText("Save Game");
        saveGameFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveGameFileMenuItem);

        optionsFileMenuItem.setText("Options");
        optionsFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(optionsFileMenuItem);

        exitFileMenuItem.setText("Exit");
        exitFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitFileMenuItem);

        mainMenu.add(fileMenu);

        helpMenu.setText("Help");

        aboutHelpMenuItem.setText("About");
        aboutHelpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutHelpMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutHelpMenuItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void loadGameFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameFileMenuItemActionPerformed
         JOptionPane.showMessageDialog(frame, "Game Loaded!\nDo you have \"Magic Cow Powers\"? NOOOO you do not!!!\nWith out them you will lose this game.\nWhy persist in this humiliating endeavor?",
                        "About Sword & Sorcery",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_loadGameFileMenuItemActionPerformed

    private void exitFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFileMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitFileMenuItemActionPerformed

    private void aboutHelpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutHelpMenuItemActionPerformed
        JOptionPane.showMessageDialog(frame, "An online, turn-based epic Swords & Sorcery strategy game.\n" +
"\n" +
"Keith Drew \"first\"\n" +
"Tao Zhang\n" +
"Matt Brown was here\n" +
"Colin Clifford\n" +
"John Goettsche\n" +
"Chihsiang Wang\n" +
"Tyler Jaszkowiak\n" +
"Cameron Simon\n" +
"David \"ReadMe Killer\" Klingenberg \n" +
"Ian Westrope\n" +
"Wayne Fuhrman","About Sword & Sorcery",
                                      JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aboutHelpMenuItemActionPerformed

    private void newGameFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameFileMenuItemActionPerformed
                JOptionPane.showMessageDialog(frame, "You started a new game.\nWith out \"Magic Cow Powers\" you will lose.",
                        "About Sword & Sorcery",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_newGameFileMenuItemActionPerformed

    private void saveGameFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameFileMenuItemActionPerformed
        JOptionPane.showMessageDialog(frame, "Game Saved!\nGood luck in finding \"Magic Cow Powers\".\nYou should save some time and just surrender now.",
                        "About Sword & Sorcery",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_saveGameFileMenuItemActionPerformed

    private void optionsFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsFileMenuItemActionPerformed
        Object[] options = {"Yes, please",
                    "No, thanks",
                    };
int n = JOptionPane.showOptionDialog(frame,
    "Still \"Magic Cow Powers\"?",
    "Options!",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    options,
    options[1]);
    }//GEN-LAST:event_optionsFileMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwordSorceryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwordSorceryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwordSorceryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwordSorceryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwordSorceryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutHelpMenuItem;
    private javax.swing.JMenuItem exitFileMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem loadGameFileMenuItem;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem newGameFileMenuItem;
    private javax.swing.JMenuItem optionsFileMenuItem;
    private javax.swing.JMenuItem saveGameFileMenuItem;
    // End of variables declaration//GEN-END:variables
}
