/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package characters;

/**
 *
 * @author chishaung
 */
public class CharacterJ extends javax.swing.JFrame {

    /**
     * Creates new form CharacterJ
     */
    public CharacterJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("#06 Eodred the Sorceress");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("#32 Sliggoth");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("#01 Gwaigillion Elengal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("#33 Mellanthia");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("#15 Chairman Naskhund");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("#22 Gerudirr Dragonslayer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("#23 Zurik Bladebreaker");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("#09 Talerren the Not-So-Brave");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("#03 Dalmilandril");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("#21 Emperor Coron III the Unconqueerable");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("#25 Zarko");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("#18 Gislan the Rock");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("#10 Jeremiah Ben Ruben");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("#04 \"X\" the Unknown (Roc Deathsinger)");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("#02 Linfalas");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("#12 Raman Cronkevitch");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("#11 Gygax Dragonlord");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("#20 Curvenol");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("#19 Wendolyn the Wary");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("#17 The Paladin Glade");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton25.setText("#28 Svartz Tarnkap");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("#27 Lord Dil");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("#26 Ganab the Nasty");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("#36 Maytwist");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton22.setText("#35 Tim the Enchanter");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("#34 Alric");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("#08 Unamit Ahazredit");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton29.setText("#07 Dierdra");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("#05 Loki Hellsson");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("#16 Snorri Gundarchuksson");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("#13 Theregond the Nage");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setText("#14 Peg-Leg Gonzo");

        jButton34.setText("#39 Stephen the Paladin");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setText("#24 Krawn the Crazy");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setText("#38 Narklath");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setText("#37 Larraka");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setText("#29 Zareth");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setText("#40 Gilith");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setText("#31 Weldron");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setText("#30 Almuric");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton16)
                    .addComponent(jButton21)
                    .addComponent(jButton10)
                    .addComponent(jButton17)
                    .addComponent(jButton32)
                    .addComponent(jButton2)
                    .addComponent(jButton33)
                    .addComponent(jButton1)
                    .addComponent(jButton24)
                    .addComponent(jButton14)
                    .addComponent(jButton18)
                    .addComponent(jButton29)
                    .addComponent(jButton9)
                    .addComponent(jButton19)
                    .addComponent(jButton31)
                    .addComponent(jButton6)
                    .addComponent(jButton13)
                    .addComponent(jButton20)
                    .addComponent(jButton15)
                    .addComponent(jButton30))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton23)
                            .addComponent(jButton22)
                            .addComponent(jButton25)
                            .addComponent(jButton26)
                            .addComponent(jButton28)
                            .addComponent(jButton27)
                            .addComponent(jButton12)
                            .addComponent(jButton35)
                            .addComponent(jButton38)
                            .addComponent(jButton40)
                            .addComponent(jButton37)
                            .addComponent(jButton36))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(63, 63, 63)))
                    .addComponent(jButton5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton41)
                            .addComponent(jButton34)
                            .addComponent(jButton39))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton11))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton27)
                        .addGap(6, 6, 6)
                        .addComponent(jButton26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(12, 12, 12)
                        .addComponent(jButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(0, 0, 0)
                        .addComponent(jButton15)
                        .addGap(0, 0, 0)
                        .addComponent(jButton30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 5/4/3\n"
                + "Magic Potential: 12\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 0540\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 0\n"
                + "Diplomatic: 3\n" 
                + "Fighting: 0\n"
                + "Endurance: 6\n"
        ); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "Successful Exit.");
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Swamp-Creature\n"
                + "Magic PL: 3/2/1\n"
                + "Magic Potential: 8\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 1314\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 2\n"
                + "Diplomatic: -1\n" 
                + "Fighting: *4\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Elf\n"
                + "Magic PL: 4/3/2\n"
                + "Magic Potential: 10\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 0630\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 3\n"
                + "Diplomatic: 6\n" 
                + "Fighting: *4\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Spider\n"
                + "Magic PL: 4/3/2\n"
                + "Magic Potential: 8\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 3808\n"
                + "Magic Profile 6\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 2\n"
                + "Diplomatic: 3\n" 
                + "Fighting: *6\n"
                + "Endurance: 12\n"
        ); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Orc\n"
                + "Magic PL: 3\n"
                + "Magic Potential: 8\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 1611\n"
                + "Magic Profile 5\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 4\n"
                + "Diplomatic: 4\n" 
                + "Fighting: *4\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Dwarf\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 2808\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 3\n"
                + "Diplomatic: 3\n" 
                + "Fighting: *6\n"
                + "Endurance: 6\n"
        ); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Dwarf\n"
                + "Magic PL: 5/4/3\n"
                + "Magic Potential: 12\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 2517\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 2\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 3\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 0803\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 4\n"
                + "Diplomatic: 3\n" 
                + "Fighting: *5\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Elf\n"
                + "Magic PL: 5/4/3\n"
                + "Magic Potential: 12\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 0319\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 1\n"
                + "Diplomatic: 2\n" 
                + "Fighting: *2\n"
                + "Endurance: 5\n"
        ); 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 0552\n"
                + "Magic Profile 6\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 5\n"
                + "Diplomatic: 3\n" 
                + "Fighting: *6\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Orc\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 1605\n"
                + "Magic Profile 2\n"
                + "Magic Resistance: 2\n"
                + "Leadership: 2\n"
                + "Diplomatic: -1\n" 
                + "Fighting: 3\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Dwarf\n"
                + "Magic PL: 4\n"
                + "Magic Potential: 8\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 0818\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 2\n"
                + "Diplomatic: 4\n" 
                + "Fighting: 4\n"
                + "Endurance: 10\n"
        ); 
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 2\n"
                + "Magic Potential: 8\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 2133\n"
                + "Magic Profile 2\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 4\n"
                + "Diplomatic: 6\n" 
                + "Fighting: 4\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 6\n"
                + "Magic Potential: 20\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 0904\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 5\n"
                + "Leadership: 1\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 0\n"
                + "Endurance: 6\n"
        ); 
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Elf\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 3426\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 4\n"
                + "Diplomatic: 4\n" 
                + "Fighting: 5\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Demi-Cronk\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 2151\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 3\n"
                + "Diplomatic: 1\n" 
                + "Fighting: *4\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Dragon\n"
                + "Magic PL: 3/2/1\n"
                + "Magic Potential: 6\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 0302\n"
                + "Magic Profile 6\n"
                + "Magic Resistance: 5\n"
                + "Leadership: 3\n"
                + "Diplomatic: 3\n" 
                + "Fighting: 7\n"
                + "Endurance: 15\n"
        ); 
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 5\n"
                + "Magic Potential: 16\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 0352\n"
                + "Magic Profile 5\n"
                + "Magic Resistance: 2\n"
                + "Leadership: 1\n"
                + "Diplomatic: 0\n" 
                + "Fighting: 0\n"
                + "Endurance: 5\n"
        ); 
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 4/3/2\n"
                + "Magic Potential: 15\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 1528\n"
                + "Magic Profile 2\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 0\n"
                + "Diplomatic: -1\n" 
                + "Fighting: 1\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 0452\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 3\n"
                + "Diplomatic: 4\n" 
                + "Fighting: 4\n"
                + "Endurance: 10\n"
        ); 
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 2\n"
                + "Magic Potential: 8\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 2151\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 2\n"
                + "Diplomatic: 3\n" 
                + "Fighting: *4\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 0451\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 2\n"
                + "Diplomatic: 3\n" 
                + "Fighting: 5\n"
                + "Endurance: 10\n"
        ); 
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Goblin\n"
                + "Magic PL: 4/3/2\n"
                + "Magic Potential: 12\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 1909\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 2\n"
                + "Leadership: 2\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 3\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Elf\n"
                + "Magic PL: 3\n"
                + "Magic Potential: 10\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 3333\n"
                + "Magic Profile 2\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 0\n"
                + "Diplomatic: 3\n" 
                + "Fighting: 0\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 5/4/3\n"
                + "Magic Potential: 16\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 0245\n"
                + "Magic Profile 6\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 0\n"
                + "Diplomatic: 1\n" 
                + "Fighting: 0\n"
                + "Endurance: 6\n"
        ); 
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 4/3/2\n"
                + "Magic Potential: 11\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 0509\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 0\n"
                + "Diplomatic: 1\n" 
                + "Fighting: 0\n"
                + "Endurance: 6\n"
        ); 
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 5/4/3\n"
                + "Magic Potential: 13\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 3150\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 3\n"
                + "Diplomatic: 3\n" 
                + "Fighting: 3\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 3638\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 2\n"
                + "Leadership: 3\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 4\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 6\n"
                + "Magic Potential: 20\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 0606\n"
                + "Magic Profile 6\n"
                + "Magic Resistance: 5\n"
                + "Leadership: 5\n"
                + "Diplomatic: 4\n" 
                + "Fighting: 6\n"
                + "Endurance: 11\n"
        ); 
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 3531\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 3\n"
                + "Diplomatic: 4\n" 
                + "Fighting: 5\n"
                + "Endurance: 7\n"
        ); 
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 4/3/2\n"
                + "Magic Potential: 14\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 2133\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 1\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 1\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Orc\n"
                + "Magic PL: 1\n"
                + "Magic Potential: 6\n"
                + "Magic Color: Yellow\n" 
                + "Home Hex: 1614\n"
                + "Magic Profile 4\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 3\n"
                + "Diplomatic: 5\n" 
                + "Fighting: *4\n"
                + "Endurance: 10\n"
        ); 
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 2433\n"
                + "Magic Profile 1\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 3\n"
                + "Diplomatic: 2\n" 
                + "Fighting: *5\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 2/1/0\n"
                + "Magic Potential: 6\n"
                + "Magic Color: Blue\n" 
                + "Home Hex: 2341\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 3\n"
                + "Diplomatic: 1\n" 
                + "Fighting: *3\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 1246\n"
                + "Magic Profile 5\n"
                + "Magic Resistance: 5\n"
                + "Leadership: 1\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 4\n"
                + "Endurance: 9\n"
        ); 
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Half-Elf\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 0302\n"
                + "Magic Profile 1\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 2\n"
                + "Diplomatic: 3\n" 
                + "Fighting: *4\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 0\n"
                + "Magic Potential: 0\n"
                + "Magic Color: None\n" 
                + "Home Hex: 0950\n"
                + "Magic Profile 3\n"
                + "Magic Resistance: 3\n"
                + "Leadership: 2\n"
                + "Diplomatic: 2\n" 
                + "Fighting: 5\n"
                + "Endurance: 10\n"
        ); 
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Wraith\n"
                + "Magic PL: 3/2/1\n"
                + "Magic Potential: 13\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 3645\n"
                + "Magic Profile 1\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 2\n"
                + "Diplomatic: -1\n" 
                + "Fighting: *4\n"
                + "Endurance: 8\n"
        ); 
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
                javax.swing.JOptionPane.showMessageDialog(null, 
                "Racial: Human\n"
                + "Magic PL: 6/5/4/\n"
                + "Magic Potential: 17\n"
                + "Magic Color: Red\n" 
                + "Home Hex: 3713\n"
                + "Magic Profile 5\n"
                + "Magic Resistance: 4\n"
                + "Leadership: 1\n"
                + "Diplomatic: 0\n" 
                + "Fighting: 0\n"
                + "Endurance: 5\n"
        ); 
    }//GEN-LAST:event_jButton37ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
