@startuml
hide circle
title Overview class diagram by Clifford and Flake

Map *-- Province
Map *-- "2046" Hex
Hex -- Hex : Neighbor
Hex -- HexEdge : Adjacent
Map "Effected" -- "Effects" Spell
Spellbook *-- Spell

RandomEvents -- "effected" Map
RandomEvents "effects" -- "effected" Stack

Stack o-- Unit
Stack o-- Character

Scenario *-- Player 
Player *-- VictoryPoints
Player *-- Faction

@enduml
