@startuml

title <b>spell class diagrams</b>\nTao Zhang\nReviewed by Jay Drage
hide circle
class character{
  
}

class spell{
  +Name:        string
  +index:       int
  +PowerLevel:  int
  +ManaCost:    int
  +Range:       int 
  +Limits:      ??
  +Effects:     string
  +Select_target()
  +Cost_Mana()
}

class spell_book{
  +Spells_By_PL: string[ ]
  +Spells_By_Available_Mana: string[ ]
  +Look_up_by_PL()
  +Look_up_by_Avaiblable_Mana()
}

character <|-right-- spell_book : see Unit diagram
spell_book *-down- "32" spell
 


@enduml